install.packages("R.utils")
install.packages("Matrix")
install.packages("dplyr")
install.packages("Seurat")
install.packages("ggplot2")
install.packages("devtools")
devtools::install_version("crossmatch", version = "1.3.1", repos = "http://cran.us.r-project.org")
devtools::install_version("multicross", version = "2.1.0", repos = "http://cran.us.r-project.org")
devtools::install_github("jackbibby1/SCPA")
devtools::install_github('kevinblighe/EnhancedVolcano')
